### ISSUE TITLE
android-ndk-r9d\ndk-build" not found in PATH

### ISSUE THREAD

**Issue by D3ATHLY** [almalence/OpenCamera#11]
Hello i have problem, when i export project for .apk i get this error in eclipse;

11:11:15 ***\* Build of configuration Default for project OpenCamera ****
"C:\Users\Yasin\workspace2\android-ndk-r9d\ndk-build" NDK_DEBUG=0 
Cannot run program "C:\Users\Yasin\workspace2\android-ndk-r9d\ndk-build": Launching failed

Error: Program "C:\Users\Yasin\workspace2\android-ndk-r9d\ndk-build" not found in PATH
PATH=[C:\Users\Yasin\workspace2]

11:11:15 Build Finished (took 18ms)

someone can help me? I'm using latest ADT Eclipse

**Comment by vikasfuter** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.almalence.opencam-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libutils-image.so"
