### ISSUE TITLE
Trying to get OpenCamera running in Eclipse

### ISSUE THREAD

**Issue by patricia-idair** [almalence/OpenCamera#24]
All wise ones at almalence:

What I really need to find out is the trick you all used to get the torch to illuminate on the Galaxy S5 from your source code.  So, I cloned your project to my desktop and imported the code into Eclipse.  I created a Debug Configuration and tried to run the OpenCamera project in debug mode.  But then I receive this error:  Could not find OpenCamera.apk!  Probably a noob question!  Can somebody tell me what I need to do to get OpenCamera running in either Eclipse or AndroidStudio?

Thank you.

**Comment by almalence** [comment]
Hi!

You need to install sdk and ndk. Set correct path to ndk. Check when builidng that native part buil successfully - check in console window.
After that in bin folder you should see OpenCamer.apk file. And using Run as... should work.

**Comment by patricia-idair** [comment]
Hi, almalence:

Oh, wise one!  Thank you for helping me to get the project running in debug mode.  But I need GOD, now, to help me figure out how you are getting the torch to turn on.  There is so much code here, I am having trouble finding what I need to look at.

Thank you.

**Comment by patricia-idair** [comment]
Hi, almalence:

OK!  in AlmalenceGUI, I found the method setFlashMode.  The int newMode is 2 for Torch.  CameraController.setCameraFlashMode(newMode) is called to set the new parameter.  It looks like you commit the change to preferences and that is it.  

I'm guessing that perhaps the problem we are having is that the torch is set before we display the preview and that may be the reason why we cannot get the torch to light for the Samsung Galaxy S5 and you can.  I'm all ears if you have any information regarding this.

Thank you.
