### ISSUE TITLE
Auto rotation of icons

### ISSUE THREAD

**Issue by Immortalin** [almalence/OpenCamera#28]
It would be nice if the icons can auto rotate depending on orientation.

**Comment by almalence** [comment]
Please be more concrete... which icons are you talking about? it's already rotating.

**Comment by Immortalin** [comment]
Apologies for the erroneous post, some things wasn't working on first startup. Things are now mostly working after a power cycle. :D

**Comment by almalence** [comment]
Let us know what icons weren't working and you device model and Android version.
