### ISSUE TITLE
HDR mode

### ISSUE THREAD

**Issue by Immortalin** [almalence/OpenCamera#29]
It would be really great if open camera can take HDR photos.

**Comment by almalence** [comment]
did you check it? :) It's already available.

**Comment by Immortalin** [comment]
I can't seem to find it though. Which setting is it under?

**Comment by almalence** [comment]
bottom right control.- allows to change modes. You will find HDR there.

**Comment by Immortalin** [comment]
It is not shown on mine though. Maybe it's a bug?

**Comment by almalence** [comment]
Send your screenshot and device info (android version and device model)

**Comment by Immortalin** [comment]
![screenshot_2015-09-06-14-08-16](https://cloud.githubusercontent.com/assets/7126128/9702856/3803f470-54a1-11e5-8c99-171540215ea9.png)

Android kitkat 4.4.2
Galaxy S4 i9506 ks01lte

**Comment by almalence** [comment]
You're talking about OpenCamera from sourceforge. We're another project OpenCamera (A Better Camera on Play Market).
You should redirect your request to correct developer.

**Comment by Immortalin** [comment]
Oops. Apologies.
