### ISSUE TITLE
Photo file name based on counter

### ISSUE THREAD

**Issue by ywemay** [almalence/OpenCamera#30]
I wonder if it is possible to append the possibility to have the filenames of photos named using a counter. By "counter" I mean that the photos will get names like: IMG_0001, IMG_0002 ... IMG_9999. Also if is possible to have the name of the next photo displayed on screen during shutting.

Such feature appears to me to be useful when one want to take photos and then make records in a notebook connected to the name of taken photos.

Please excuse me if this request is inappropriate for the "issues" section - I'm really not sure.

**Comment by almalence** [comment]
Thanks. We'll review this feature.
