### ISSUE TITLE
Project's license?

### ISSUE THREAD

**Issue by eneim** [almalence/OpenCamera#32]
Excuse me, I could not get the correct LICENSE information. Could you please specify more about that? Thanks in advance.

**Comment by almalence** [comment]
Hi!

All code is under MPL, CameraController classes are under GNU GPLv3.
Also some processing plugins are using our proprietary library - trial version available on github.

**Comment by eneim** [comment]
Thanks for response, I wanted to know in case I would like to contribute to it or event use parts of it in commercial :D. Now it's more clear for me.
