### ISSUE TITLE
ImageConversionUtils.h: No such file or directory

### ISSUE THREAD

**Issue by sagaratalatti** [almalence/OpenCamera#35]
Returns Error for bestshot.cpp

Cannot find these files

#include "ImageConversionUtils.h"

#include "bestshot.h"

**Comment by almalence** [comment]
It's located in jni folder.

Also note, that bestshot is using our propietary library.

**Comment by sagaratalatti** [comment]
I am using Android Studio to build the project. Yes I found the libraries in the jni folder. But still its giving error for 

#include "ImageConversionUtils.h"
#include "bestshot.h"

**Comment by erkandiken** [comment]
Could you please clarify how to add include paths for ndk files in android studio environment, android build complains that it can not find the "*.h" files as mentioned in the first post ? 

Thank you in advance.

**Comment by almalence** [comment]
it should be smth like this

    sourceSets.main {
        jni.srcDirs = [] // This prevents the auto generation of Android.mk
        jniLibs.srcDir 'src/main/libs' // This is not necessary unless you have precompiled libraries in your project.
    }

    task buildNative(type: Exec, description: 'Compile JNI source via NDK') {
        def ndkDir = android.ndkDirectory
        commandLine "$ndkDir/ndk-build.cmd",
                '-C', file('src/main/jni').absolutePath, // Change src/main/jni the relative path to your jni source
                '-j', Runtime.runtime.availableProcessors(),
                'all',
                'NDK_DEBUG=1'
    }

    task cleanNative(type: Exec, description: 'Clean JNI object files') {
        def ndkDir = android.ndkDirectory
        commandLine "$ndkDir/ndk-build.cmd",
                '-C', file('src/main/jni').absolutePath, // Change src/main/jni the relative path to your jni source
                'clean'
    }


Currently we have probems with migration connected with our internal needs and current limitations of Android Studio.

**Comment by Zihuatanejo50** [comment]
@almalence Thank you very much，solve my problem!

**Comment by kwosu87** [comment]
@almalence If you use by Android Studio, you should change `ndk-build.cmd` -> `ndk-build`.
