### ISSUE TITLE
Premium unlocker

### ISSUE THREAD

**Issue by kularny** [almalence/OpenCamera#39]
I compiled the apk and with libs and android. Mk i put it my android source which gets copied to the system/app... Now if i buy the premium it adds another icon and another spp... Kindly can make an unlocker like poweramp player has... Which unlocks the app and then hides itself from the launcher window.

**Comment by almalence** [comment]
Hi

Please specify what do you need?

**Comment by kularny** [comment]
See.. After i compile the rom.. The apk gets placed in systen/app... Now if i try to buy the product for unlocking premium stuff it downloads another same app... So now i have two apps on the launcher menu named a better camera.. One which i supplied.. Other that i downloaded.. I want u to make a simple unlocker app... Not the whole app... A small unlocker app that unlocks the current installed app in system and then hides itself from the launcher window....now if i buy the app.. I get two similar apps placed in the menu of android launcher

**Comment by almalence** [comment]
What is the purpose of all these actions?

1. Application has library which is proprietary. Github has evaluation version which will add watermark.
2. We will not provide you with such app.
3. Unlcoked version from the arket will unlock free version because user payed for it.

**Comment by kularny** [comment]
Why are u not getting me... I said iam ready to pay...but make an app that unlocks the trial one without having to redownload an entire app. U can put rhe unlocker in PS instead of the whole app.

**Comment by almalence** [comment]
I got your idea, but you didn't describe whole idea - what is it for? What are you trying to do? Are you going to provide this ROM to other users or what?

As I said it will not work, just unlocking. There should be another version of library which is available only in exported version of application on markets.

**Comment by kularny** [comment]
Yes ur correct... Iam the developer of dirtyunicorns for i9100...i have my own custom kernel and stuff and i always look to offer best solns to people... Iam going to provide this app with the rom as the camera2 is absolutely worthless... Its autofocus doesnt work as it lacks a mutex...for this reason only i thot maybe i can ship this app with rom which has basic functions and for advanced users can pay.. I paid for ur app yesterday and when i uninstalled it just to fix some stuff and later install it... The whole money got refunded which i didnt intend to.. Thats why iam asking u for this soln...like its available by drfault on roms and user who wants to unlock can simply can by buying it off playstore...u can symlink ur library frm thr data partition to the system where ur unlock libs will be placed... As u knw system is ro.

**Comment by almalence** [comment]
Generally we can provide you fulll featured unlocked version. And you can integrate it into your ROM. What do you think?

We can also provide it for all devices, not only for S2.

**Comment by kularny** [comment]
Then it will be of a great help from u guys and probably the biggest contribution for our s2 community. As u guys knw cm13 switched to snap camera from camera2 doesn't provide  basic functions like panorama and has a broken autofocus lock..i will really appreciate u guys if u can help and provide with a full unlocked version. Thanks.

**Comment by almalence** [comment]
Please contact me directly - sergey.malykhin@almalence.com

**Comment by kularny** [comment]
I left a message for you in the mentioned email. Thanks.
