### ISSUE TITLE
ISO settings

### ISSUE THREAD

**Issue by DiegoCatalano** [almalence/OpenCamera#46]
Hello Developers,

There's something strange going on, I got a Zenfone 2 ZE551ML, the asus pixelmaster camera has manual mode that I can change the iso values. But for some reason, the OpenCamera and the Android API 21, return null to SENSOR_INFO_SENSITIVITY_RANGE.

Anyone know why this occurs?

**Comment by almalence** [comment]
Hi

Provide us camera parameters to see what your camera supports.

**Comment by DiegoCatalano** [comment]
This is all the camera parameters:

flash-mode = off
Xe_exposure_time = 0
focus_range_values = 5~100
**Xe_Iso** = 0
effect-values = none
flash-mode-values = auto
exposure-compensation = 0
preview-size = 640x480
max-num-detected-faces-hw = 32
preview_color_temp = 2500~10000
preview-fps-range = 4000
jpeg-thumbnail-size-values = 320x240
focal-length = 3.780000
focus-distances = 2
picture-format-values = jpeg
video-size = 1920x1080
Xe_brightness = 0
zoom-supported = true
preview-frame-rate = 30
max-exposure-compensation = 6
scene-mode = auto
picture-size = 320x240
max-zoom = 476
zoom = 0
rotation = 0
jpeg-thumbnail-quality = 50
antibanding = auto
video-frame-format = yuv420sp
shutter_speed_values = 2
exposure-compensation-step = 0.33333333
jpeg-quality = 90
whitebalance = auto
effect = none
jpeg-thumbnail-width = 320
auto-exposure-lock = false
scene-mode-values = auto
video-size-values = 176x144
preview-fps-range-values = (4000
preview-format = yuv420sp
whitebalance-values = auto
focus-mode-values = auto
max-num-metering-areas = 1
vertical-view-angle = 42.5
metering-areas = (0,0,0,0)
auto-exposure-lock-supported = true
zoom-ratios = 100
focus-areas = (0,0,0,0)
picture-size-values = 320x240
horizontal-view-angle = 61.8
antibanding-values = off
auto-whitebalance-lock = false
ae-metering-mode = auto
video-stabilization = false
min-exposure-compensation = -6
video-stabilization-supported = false
focus-mode = auto
video-snapshot-supported = true
preview-frame-rate-values = 30
preview-format-values = yuv420sp
preferred-preview-size-for-video = 1280x720
picture-format = jpeg
jpeg-thumbnail-height = 240
preview-size-values = 1920x1080
max-num-focus-areas = 9
auto-whitebalance-lock-supported = true

I think the parameter Xe_iso can handle the iso values, but is strange because I cannot get the possible values. I don't have idea what means too.

Thanks !

**Comment by almalence** [comment]
Xe_Iso doesn't tell about anything. The problem is that iso API is not standardized and any manufacturer can do whatever they want.

**Comment by DiegoCatalano** [comment]
Ok, I agree with you, but It's strange because the PixelMaster allow to handle with iso and shutter speed.

http://www.asus-zenfone.com/2015/02/review-asus-zenfone-2-camera-manual-mode.html

I don't know why the android can't retrieve there parameters.
