### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LosDanieloss** [almalence/OpenCamera#47]
Hi,
I know there is a license file in this repo but as english is not my native language and my english is rather bad I have trouble understanding that is it possible to convert this app into library module and use in commercial app without providing source code of the whole app?

**Comment by almalence** [comment]
Hi

You can use code which is under MPL.

CameraController in under GPL, so you have to open all your code in order to use it.

Also we're using proprietary library for dro, super, hdr, night, multishots, bestshot, panorama, hdr video. Evaluation copy only is available on github.

**Comment by rugk** [comment]
Also have a look at https://tldrlegal.com/

I think that's the easiest way to understand licenses.
.
You can also have a look at your local Wikipedia. Maybe you see an article about the license there. Just search for the name of the license.

Alternatively there could be a "simple English" Wikipedia article about the license.

**Comment by rugk** [comment]
BTW: in the Readme the title "Mozilla public license" is not mentioned. This makes it hard to easily get out which license it is.
So what about adding this?

**Comment by jn0** [comment]
This code resembles to http://opencamera.sourceforge.net/ which is **GPLv3** (since 2013).
I ain't sure, if this somehow commercial product match the terms of the original code's license...
Please, clarify.

**Comment by rugk** [comment]
> This code resembles to http://opencamera.sourceforge.net/ which is GPLv3 (since 2013).

But that's not said in the license file. And if this GitHub project really uses code from there relicensing it under the MPL is clearly be a copyright infringement. 
Actually I find it strange to discover this project on Sourceforge too. Especially they also link to FDroid for downloading where there is actually no download for the GPL version, but only for this version here.

**Comment by almalence** [comment]
Project on sourceforge is not connected to us. It's standalone project developed by independent developer. We're not using his code and he is not using our's, these are 2 different projects, but same name. In our case Almalence's Open camera on github is a name of repository and opensource part, on which A Better Camera project based.

**Comment by rugk** [comment]
Thanks for the clarification. Howver it's still notable how similar the screenshots are...

**Comment by almalence** [comment]
@rugk we're working on this project since February 2012 :)
First hen we found it, we thought it was stolen, especially some icons... the main question is about shutter button!
