### ISSUE TITLE
Green tint of photos on SGS6 Edge+

### ISSUE THREAD

**Issue by michskolimowski** [almalence/OpenCamera#51]
Issue connects with https://github.com/almalence/OpenCamera/issues/50 - when user is able to take photo in 2-3 second interval of app working, photo has green tint.

Issue occurs on latest release from Play Store.

**Comment by almalence** [comment]
Please resend to support - support@abc.almalence.com

Also specify exact model name and android version. Camera parameters would be also useful - settings.general/more/camera parameters
