### ISSUE TITLE
how to use this project as library in my application

### ISSUE THREAD

**Issue by AndroidDeveloper3** [almalence/OpenCamera#63]
In my application i want to capture an image. So i want to capture image with this app instead of default camera. Is it possible?

**Comment by Nsmtechnicals** [comment]
Yes, you can use it to take pictures...



Team NsmTechnicals

________________________________

**Comment by AndroidDeveloper3** [comment]
I have added this project as module, and getting error as shown below

Error:Execution failed for task ':openCamera:compileReleaseRenderscript'.
> com.android.ide.common.process.ProcessException: Error while executing 'E:\Softwares\sdk1\build-tools\25.0.3\llvm-rs-cc.exe' with arguments {-O 3 -I E:\Softwares\sdk1\build-tools\25.0.3\renderscript\include\ -I E:\Softwares\sdk1\build-tools\25.0.3\renderscript\clang-include\ -p D:\SVN-WORKS\MyApplication\openCamera\build\generated\source\rs\release -o D:\SVN-WORKS\MyApplication\openCamera\build\generated\res\rs\release\raw -target-api 15 D:\SVN-WORKS\MyApplication\openCamera\src\main\rs\align_mtb.rs D:\SVN-WORKS\MyApplication\openCamera\src\main\rs\create_mtb.rs D:\SVN-WORKS\MyApplication\openCamera\src\main\rs\histogram_adjust.rs D:\SVN-WORKS\MyApplication\openCamera\src\main\rs\histogram_compute.rs D:\SVN-WORKS\MyApplication\openCamera\src\main\rs\process_hdr.rs}
