### ISSUE TITLE
No Photo while moving

### ISSUE THREAD

**Issue by teatimetom** [almalence/OpenCamera#87]
I can't take pictures while I'm moving the phone. Only when I hold the phone still is the recording triggered.
I like to take pictures on the move while passing by.

**Comment by SebLui** [comment]
Have you found a solution for this? Same problem with me and it's annoying. I use it on FP4

**Comment by Gitoffthelawn** [comment]
@SebLui You may want to create a new issue or ask for this one to be reopened.

**Comment by SebLui** [comment]
created a new issue (https://github.com/almalence/OpenCamera/issues/109)
